countries = ['AUSTRALIA', 'ARGENTINA', 'BRAZIL', 'CANADA', 'DENMARK', 'FINLAND', 'GERMANY', 'HUNGARY', 'IRELAND', 'JAMAICA', 'KAZAKHSTAN', 'LUXEMBOURG', 'MALAYSIA', 'NETHERLANDS', 'PHILIPPINES', 'RUSSIA', 'SINGAPORE', 'THAILAND', 'UKRAINE', 'VENEZUELA']

animals = ['GIRAFFE', 'KANGAROO', 'ELEPHANT', 'GORILLA', 'KOALA', 'PANDA', 'PENGUIN', 'LEOPARD', 'CHEETAH', 'HYENA', 'HIPPOPOTAMUS', 'PORCUPINE', 'RACCOON', 'SQUIRREL', 'LION', 'RHINOCEROS', 'TOUCAN', 'ZEBRA', 'CROCODILE', 'FLAMINGO']

fruits = ['AVOCADO', 'BLACKBERRY', 'CHERRY', 'COCONUT', 'DRAGONFRUIT', 'FIG', 'GRAPEFRUIT', 'HONEYDEW', 'KIWI', 'LYCHEE', 'MANGO', 'NECTARINE', 'ORANGE', 'PAPAYA', 'PINEAPPLE', 'RASPBERRY', 'STRAWBERRY', 'TANGERINE', 'WATERMELON', 'BANANA']

sports = ['ARCHERY', 'BADMINTON', 'BASKETBALL', 'BOXING', 'CRICKET', 'FENCING', 'FOOTBALL', 'GOLF', 'HOCKEY', 'JUDO', 'KARATE', 'ROWING', 'SAILING', 'SKATEBOARDING', 'SKIING', 'SWIMMING', 'TENNIS', 'VOLLEYBALL', 'WRESTLING', 'SNOWBOARDING']

professions = ['ASTRONAUT', 'CHEF', 'DENTIST', 'ELECTRICIAN', 'FIREFIGHTER', 'GEOLOGIST', 'JOURNALIST', 'LIBRARIAN', 'MECHANIC', 'NURSE', 'OPTOMETRIST', 'PHARMACIST', 'PILOT', 'RADIOLOGIST', 'SCIENTIST', 'SURGEON', 'TEACHER', 'VETERINARIAN', 'ZOOLOGIST', 'PSYCHOLOGIST']

instruments = ['GUITAR', 'PIANO', 'VIOLIN', 'DRUMS', 'TRUMPET', 'SAXOPHONE', 'FLUTE', 'CLARINET', 'ACCORDION', 'TROMBONE', 'HARMONICA', 'UKULELE', 'BANJO', 'MANDOLIN', 'HARPSICHORD', 'MARACAS', 'XYLOPHONE', 'BASSOON', 'CELLO', 'HARP']

brands = ['NINTENDO', 'ADIDAS', 'MICROSOFT', 'PLAYSTATION', 'VOLKSWAGEN', 'APPLE', 'GOOGLE', 'FERRARI', 'AMAZON', 'MCDONALDS', 'MERCEDES', 'HERSHEY', 'LAMBORGHINI', 'SAMSUNG', 'CHAMPION', 'DISNEY', 'MOTOROLA', 'TOYOTA', 'NETFLIX']

cities = ["PHOENIX", "CHICAGO", "SEATTLE", "TORONTO", "LONDON", "PARIS", "DALLAS", "BERLIN", "TOKYO", "SYDNEY", "PHILADELPHIA", "SINGAPORE", "ISTANBUL", "MOSCOW", "DUBAI", "PORTLAND", "BEIJING", "MUMBAI", "HOUSTON", "JOHANNESBURG"]

