countries = [
    'AUSTRALIA',
    'ARGENTINA',
    'BRAZIL',
    'CANADA',
    'DENMARK',
    'FINLAND',
    'GERMANY',
    'HUNGARY',
    'IRELAND',
    'JAMAICA',
    'KAZAKHSTAN',
    'LUXEMBOURG',
    'MALAYSIA',
    'NETHERLANDS',
    'PHILIPPINES',
    'RUSSIA',
    'SINGAPORE',
    'THAILAND',
    'UKRAINE',
    'VENEZUELA',
    'UNITED STATES',
    'SOUTH AFRICA',
    'NEW ZEALAND',
    'UNITED KINGDOM',
    'UNITED STATES',
    'SAUDI ARABIA',
    'CZECH REPUBLIC',
    'SOUTH KOREA',
    'COSTA RICA',
    'DOMINICAN REPUBLIC',
    'SRI LANKA',
    'FRANCE'
]

animals = [
    'GIRAFFE',
    'KANGAROO',
    'ELEPHANT',
    'GORILLA',
    'KOALA',
    'PANDA',
    'PENGUIN',
    'LEOPARD',
    'CHEETAH',
    'HYENA',
    'PORCUPINE',
    'RACCOON',
    'SQUIRREL',
    'LION',
    'RHINOCEROS',
    'TOUCAN',
    'ZEBRA',
    'CROCODILE',
    'FLAMINGO',
    'BLACK BEAR',
    'POLAR BEAR',
    'TIGER',
    'RED FOX',
    'BALD EAGLE',
    'BLUE WHALE',
    'ORANGUTAN',
    'SHARK',
    'KILLER WHALE',
    'HUMPBACK WHALE'
]

fruits = [
    'AVOCADO',
    'BLACKBERRY',
    'CHERRY',
    'COCONUT',
    'DRAGONFRUIT',
    'GRAPEFRUIT',
    'HONEYDEW',
    'KIWI',
    'LYCHEE',
    'MANGO',
    'NECTARINE',
    'ORANGE',
    'PAPAYA',
    'PINEAPPLE',
    'RASPBERRY',
    'STRAWBERRY',
    'TANGERINE',
    'WATERMELON',
    'BANANA',
    'BLUEBERRY',
    'PEACH',
    'PLUM',
    'PEAR',
    'APPLE',
    'GRAPE',
    'LEMON',
    'LIME',
    'POMEGRANATE'
]

sports = [
    'ARCHERY',
    'BADMINTON',
    'BASKETBALL',
    'BOXING',
    'CRICKET',
    'FENCING',
    'FOOTBALL',
    'GOLF',
    'HOCKEY',
    'JUDO',
    'KARATE',
    'LACROSSE',
    'ROWING',
    'SAILING',
    'SKIING',
    'SURFING',
    'SWIMMING',
    'TENNIS',
    'VOLLEYBALL',
    'WRESTLING',
    'SURFING',
    'BASEBALL',
    'RUGBY',
    'CYCLING',
    'GYMNASTICS',
    'TABLE TENNIS',
    'TRACK AND FIELD',
    'WATER POLO',
]

professions = [
    'ASTRONAUT',
    'CHEF',
    'DENTIST',
    'ELECTRICIAN',
    'FIREFIGHTER',
    'GEOLOGIST',
    'JOURNALIST',
    'LIBRARIAN',
    'MECHANIC',
    'NURSE',
    'OPTOMETRIST',
    'PHARMACIST',
    'PILOT',
    'RADIOLOGIST',
    'SCIENTIST',
    'SURGEON',
    'TEACHER',
    'ZOOLOGIST',
    'SOFTWARE ENGINEER',
    'GRAPHIC DESIGNER',
    'MARKETING MANAGER',
    'ARCHITECT',
    'LAWYER',
    'ACCOUNTANT',
    'SOCIAL WORKER',
    'CHEMIST',
    'POLICE OFFICER',
    'PLUMBER',
    'CARPENTER',
    'PROFESSOR',
    'ARCHITECT',
    'TECHNICIAN'
]

instruments = [
    'GUITAR',
    'PIANO',
    'VIOLIN',
    'DRUMS',
    'TRUMPET',
    'SAXOPHONE',
    'FLUTE',
    'CLARINET',
    'ACCORDION',
    'TROMBONE',
    'HARMONICA',
    'UKULELE',
    'BANJO',
    'MANDOLIN',
    'HARPSICHORD',
    'MARACAS',
    'XYLOPHONE',
    'BASSOON',
    'CELLO',
    'HARP',
    'ELECTRIC GUITAR',
    'FRENCH HORN',
    'VIOLA',
    'BAGPIPES',
    'OBOE',
    'SITAR',
    'TUBA',
    'KALIMBA',
    'DIDGERIDOO'
]

brands = [
    'NINTENDO',
    'ADIDAS',
    'MICROSOFT',
    'PLAYSTATION',
    'VOLKSWAGEN',
    'APPLE',
    'GOOGLE',
    'FERRARI',
    'AMAZON',
    'MCDONALDS',
    'MERCEDES',
    'HERSHEY',
    'LAMBORGHINI',
    'SAMSUNG',
    'CHAMPION',
    'DISNEY',
    'MOTOROLA',
    'TOYOTA',
    'NETFLIX',
    'COCA COLA',
    'PEPSI',
    'NIKE',
    'GUCCI',
    'SPOTIFY',
    'UNDER ARMOUR',
    'DUNKIN DONUTS',
    'BURGER KING',
    'KENTUCKY FRIED CHICKEN',
    'TOMMY HILFIGER',
    'LOUIS VUITTON',
    'CALVIN KLEIN',
    'TESLA'
]

cities = [
    'ATLANTA',
    'PHOENIX',
    'CHICAGO',
    'SEATTLE',
    'TORONTO',
    'LONDON',
    'PARIS',
    'DALLAS',
    'BERLIN',
    'TOKYO',
    'SYDNEY',
    'SINGAPORE',
    'ISTANBUL',
    'MOSCOW',
    'DUBAI',
    'PORTLAND',
    'BEIJING',
    'MUMBAI',
    'HOUSTON',
    'NEW YORK',
    'LOS ANGELES',
    'ROME',
    'MADRID',
    'AMSTERDAM',
    'VIENNA',
    'BANGKOK',
    'DELHI',
    'RALEIGH',
    'ATHENS',
    'HOUSTON',
    'KANSAS CITY',
    'BALTIMORE',
    'MIAMI',
    'LAS VEGAS',
    'SHANGHAI',
    'BANGKOK',
    'BARCELONA',
    'PRAGUE'
]

movies = [
    'AVATAR',
    'TITANIC',
    'STAR WARS',
    'JURASSIC PARK',
    'THE LORD OF THE RINGS',
    'INCEPTION',
    'THE MATRIX',
    'HARRY POTTER',
    'THE GODFATHER',
    'FROZEN',
    'THE DARK KNIGHT',
    'THE AVENGERS',
    'FORREST GUMP',
    'THE SHAWSHANK REDEMPTION',
    'THE LION KING',
    'PULP FICTION',
    'GLADIATOR',
    'THE DEPARTED',
    'BACK TO THE FUTURE',
    'GOODFELLAS',
    'CASINO',
    'THE SILENCE OF THE LAMBS',
    'FIGHT CLUB',
    'THE WIZARD OF OZ',
    'PIRATES OF THE CARIBBEAN',
    'THE TERMINATOR',
    'THE NOTEBOOK',
    'MULAN'
]

books = [
    'TO KILL A MOCKINGBIRD',
    'PRIDE AND PREJUDICE',
    'A SERIES OF UNFORTUNATE EVENTS',
    'THE GREAT GATSBY',
    'THE HOBBIT',
    'HARRY POTTER',
    'THE CATCHER IN THE RYE',
    'THE LORD OF THE RINGS',
    'ANIMAL FARM',
    'THE ALCHEMIST',
    'TO THE LIGHTHOUSE',
    'THE ADVENTURES OF HUCKLEBERRY FINN',
    'WAR AND PEACE',
    'THE CATCHER IN THE RYE',
    'THE DA VINCI CODE',
    'THE GIRL WITH THE DRAGON TATTOO',
    'THE HUNGER GAMES',
    'TO KILL A MOCKINGBIRD',
    'BRIDGE TO TERABITHIA',
    'OF MICE AND MEN',
    'GONE WITH THE WIND',
    'A TALE OF TWO CITIES',
]

tv_shows = [
    'FRIENDS',
    'GAME OF THRONES',
    'BREAKING BAD',
    'THE SIMPSONS',
    'STRANGER THINGS',
    'THE WALKING DEAD',
    'THE OFFICE',
    'FAMILY GUY',
    'THE BIG BANG THEORY',
    'WESTWORLD',
    'BLACK MIRROR',
    'FARGO',
    'NARCOS',
    'SHERLOCK',
    'HOUSE OF CARDS',
    'HOW I MET YOUR MOTHER',
    'LOST',
    'THE CROWN',
    'THE HANDMAIDS TALE',
    'MONEY HEIST',
    'THE WIRE',
    'THE SOPRANOS',
    'SOUTH PARK',
    'SEINFELD',
    'BAND OF BROTHERS',
    'RICK AND MORTY',
    'THE TWILIGHT ZONE',
    'TED LASSO',
    'PEAKY BLINDERS',
]

alcohol = [
    'VODKA',
    'RUM',
    'WHISKEY',
    'TEQUILA',
    'BRANDY',
    'SCOTCH',
    'BOURBON',
    'WINE',
    'BEER',
    'SAKE',
    'CHAMPAGNE',
    'COGNAC',
    'ABSINTHE',
    'RUM',
    'VODKA',
    'TEQUILA',
    'WHISKEY',
    'SELTZER',
    'CIDER',
    'VERMOUTH',
    'MOONSHINE',
    'LAGER',
    'STOUT',
    'INDIA PALE ALE',
    'PILSNER',
    'PORTER'
]

